"""add_audit_events_table

Revision ID: 1dd9e3eb447c
Revises: 9f07e0ba0c42
Create Date: 2025-12-17 01:43:10.913841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd9e3eb447c'
down_revision: Union[str, None] = '9f07e0ba0c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('actor_api_key_id', sa.String(), nullable=True),
    sa.Column('old_data_json', sa.Text(), nullable=True),
    sa.Column('new_data_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_collection_id'), 'audit_events', ['collection_id'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_collection_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
