"""add_validation_rules_table

Revision ID: 5ecbf89c4fb1
Revises: d20a13efde47
Create Date: 2025-12-17 03:01:06.901489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecbf89c4fb1'
down_revision: Union[str, None] = 'd20a13efde47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_field_id'), 'validation_rules', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_rules_field_id'), table_name='validation_rules')
    op.drop_table('validation_rules')
    # ### end Alembic commands ###
