"""add_relation_fields

Revision ID: 91620f7c26f6
Revises: f3d1b785b3ef
Create Date: 2025-12-17 02:47:36.225469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91620f7c26f6'
down_revision: Union[str, None] = 'f3d1b785b3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('relation_target_collection_id', sa.String(), nullable=True))
    op.add_column('fields', sa.Column('relation_type', sa.String(length=32), nullable=True))
    op.add_column('fields', sa.Column('relation_on_delete', sa.String(length=32), nullable=True))
    op.add_column('fields', sa.Column('relation_display_field', sa.String(length=63), nullable=True))
    op.create_foreign_key(None, 'fields', 'collections', ['relation_target_collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.drop_column('fields', 'relation_display_field')
    op.drop_column('fields', 'relation_on_delete')
    op.drop_column('fields', 'relation_type')
    op.drop_column('fields', 'relation_target_collection_id')
    # ### end Alembic commands ###
