"""add_views_tables

Revision ID: d20a13efde47
Revises: 91620f7c26f6
Create Date: 2025-12-17 02:55:08.684652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20a13efde47'
down_revision: Union[str, None] = '91620f7c26f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_collection_id', sa.String(), nullable=False),
    sa.Column('projection_json', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('sorts_json', sa.Text(), nullable=True),
    sa.Column('joins_json', sa.Text(), nullable=True),
    sa.Column('params_schema_json', sa.Text(), nullable=True),
    sa.Column('default_limit', sa.Integer(), nullable=False),
    sa.Column('max_limit', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_views_project_id'), 'views', ['project_id'], unique=False)
    op.create_table('view_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('view_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('projection_json', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('sorts_json', sa.Text(), nullable=True),
    sa.Column('joins_json', sa.Text(), nullable=True),
    sa.Column('params_schema_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_versions_view_id'), 'view_versions', ['view_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_versions_view_id'), table_name='view_versions')
    op.drop_table('view_versions')
    op.drop_index(op.f('ix_views_project_id'), table_name='views')
    op.drop_table('views')
    # ### end Alembic commands ###
