"""add_schema_evolution_tables

Revision ID: f3d1b785b3ef
Revises: 47bead2fb2ac
Create Date: 2025-12-17 02:39:15.865676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d1b785b3ef'
down_revision: Union[str, None] = '47bead2fb2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('old_name', sa.String(length=63), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_aliases_collection_id'), 'collection_aliases', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_aliases_old_name'), 'collection_aliases', ['old_name'], unique=False)
    op.create_index(op.f('ix_collection_aliases_project_id'), 'collection_aliases', ['project_id'], unique=False)
    op.create_table('field_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('old_name', sa.String(length=63), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_aliases_collection_id'), 'field_aliases', ['collection_id'], unique=False)
    op.create_index(op.f('ix_field_aliases_field_id'), 'field_aliases', ['field_id'], unique=False)
    op.create_index(op.f('ix_field_aliases_old_name'), 'field_aliases', ['old_name'], unique=False)
    op.add_column('fields', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('fields', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'deleted_at')
    op.drop_column('fields', 'is_deleted')
    op.drop_index(op.f('ix_field_aliases_old_name'), table_name='field_aliases')
    op.drop_index(op.f('ix_field_aliases_field_id'), table_name='field_aliases')
    op.drop_index(op.f('ix_field_aliases_collection_id'), table_name='field_aliases')
    op.drop_table('field_aliases')
    op.drop_index(op.f('ix_collection_aliases_project_id'), table_name='collection_aliases')
    op.drop_index(op.f('ix_collection_aliases_old_name'), table_name='collection_aliases')
    op.drop_index(op.f('ix_collection_aliases_collection_id'), table_name='collection_aliases')
    op.drop_table('collection_aliases')
    # ### end Alembic commands ###
